[versions]
discord = "aliucord-SNAPSHOT"
aliucord = "bbcd8a8"
kotlin = "1.5.21"
android = "8.1.1"

[libraries]
discord = { module = "com.discord:discord", version.ref = "discord" }
aliucord = { module = "com.aliucord:Aliucord", version = "main-SNAPSHOT" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
aliucord = { id = "com.aliucord.gradle", version.ref = "aliucord" }